### ISSUE TITLE
Possible cooperation/integration with spring-loaded, Fakereplace and others?

### ISSUE THREAD

**Issue by volkertb** [HotswapProjects/HotswapAgent#168]
First of all: impressive project. Keep up the amazing work!

I was wondering if the HotswapAgent developers have been in contact with the developers of the [spring-loaded](https://github.com/spring-projects/spring-loaded) project, to discuss possible cooperation and/or the sharing of code. Could both projects somehow be made to augment one and other, or do they completely overlap? Perhaps the technical approaches of both projects are completely different and mutually incompatible?

It would be a shame to reinvent the wheel. Ideally, it would be great if we could have the best of both worlds.

This same question also applies to other open source projects that aim to facilitate hot code deployment/swapping, such as [Fakereplace](https://github.com/fakereplace/fakereplace).

What are your thoughts on this, developers? Thanks for considering.

**Comment by skybber** [comment]
Thanks! It is good to hear that people like this project. As far as FakeReplace, I was in touch with the author of FakeReplace - S.Douglas, we're using proxy reloading mechanism WeldPlugin from fakereplace - it made the work on the plugin much easier.

**Comment by volkertb** [comment]
@skybber Perhaps that would be all the more reason for the three projects to consider pooling their resources? Good to know some code is being shared with FakeReplace. How about the people at spring-loaded? Since HotswapAgent contains a lot of Spring-specific functionality, perhaps there's an opportunity for some cooperation with them as well?

**Comment by skybber** [comment]
I'm not Spring expert at all, so I don't know if SpringLoaded has some features that HA has not and vice versa. But we are totally open for new idea, new contribution and new developers. According my experience the work on this project is amazing way how to learn JVM/java/appl servers/servlet containers/frameworks, simply all the java stuff on much deeper level. Otherwise, technologicaly, HA+dcevm are potentially able to handle much more redefinition scenarios then SpringLoaded or FakeReplace.
