### ISSUE TITLE
Java 8 (9/10) support

### ISSUE THREAD

**Issue by olegchir** [HotswapProjects/HotswapAgent#173]
Could you please tell us the status of Java 8+ support in hotswapagent?
Afaik there was a lot of problems with lambdas and direct method handles in the DCEVM, and the solution is somewhere at the intersection of agent and vm

The motivation of this question:
- Can we use hotswapagent after migration to Java 8? How will the development process change?
- At the next java conference, I want to include hotswapagent to the list of the most useful tools - but it means that I have to report possible problems. The more technical details will be known, the better

**Comment by skybber** [comment]
[HotswapAgent](http://hotswapagent.org/) solves Java framework reloading, proxy and anonymous class reloading and static members (enumeration) definition. JVM (7/8) patching is done by dcevm. Dcevm8 is pretty stable since v8u112. Problems with lambdas, debugging in eclipse,netbeans etc. were fixed. I'm not aware there was a problem with direct method. BUT I'm using 8u112  on dayily basis and it is pretty stable for me. It hangs rarely especially when bunch of classes is redefined, but the same problem is in v7 as well.

**Comment by edudant** [comment]
We definitely plan to support further Java versions. Support for Java9 is discussed in #218.
