### ISSUE TITLE
Changes in class fields not working as expected - DCEVM + Hotswap

### ISSUE THREAD

**Issue by sachinkakkar7** [HotswapProjects/HotswapAgent#181]
Hi,

I am using JDK 8 + DCEVM + latest hotswap agentc+ Jboss 7. Changes related to methods - (changing method's signature, method's body, removal/addition of methods) are working fine. But the changes related to class fields aren't working as expected.
1. Adding a class field - New field is picked up but the field gets initialized to default value. 
2. Removing a class field - This works fine
3. Modifying a class field's value - Doesn't work. New change isn't picked up.

Can someone please suggest a solution for this?

Thanks,

**Comment by sachinkakkar7** [comment]
Summarizing the issues.

1. If I declare and initialize a class field, the new variable is picked up but initialization doesn't work. 
2. If I add a new class, I get NoClassDefinitionFound Error. Will creating hotswap-agent.properties solve this?

**Comment by skybber** [comment]
What do you mean by class  field? Static fields? If so, then dcevm leaves new static values unitialized  (null). There is a ClassInit [plugin in HA](https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/plugin/jvm/ClassInitPlugin.java) that initializes new static fields but leaves old values. As I mean it is correct since the value stored in survived static couldn't be get from initializer but from some other process. There is no general solution...

**Comment by sachinkakkar7** [comment]
Okay and how about the non-static fields of the class?

**Comment by skybber** [comment]
Dcevm+HA don't modify new member values of **existing instances**, they are null after definition.

**Comment by sachinkakkar7** [comment]
thanks!!
