### ISSUE TITLE
Dynamically reloading Weld injection points

### ISSUE THREAD

**Issue by svelto-spinoff** [HotswapProjects/HotswapAgent#227]
It seems to us that the Hotswap agent is not able to properly reinject classes in which injection points have been added/deleted.
Example: initially
`@Named class Foo{}
@Named class Bar{}`
then:
`@Named class Foo {@Inject private Bar bar;}`
In these cases, the Bar object is not injected in the Foo object.
We have tried changing the weld.reloadStrategy to CLASS_CHANGE, but nothing happens.
This is a pity, because it really prevents Hotswap to work properly with JSF/CDI Webapps.

**Comment by skybber** [comment]
Did you try version from repository?

**Comment by svelto-spinoff** [comment]
We have tried both the jar online (1.1.0-SNAPSHOT), and downloading and recompiling from the sources. Same behavior.

**Comment by skybber** [comment]
I've modified [test application](https://github.com/HotswapProjects/HotswapAgentExamples/tree/master/deltaspike-hibernate-jsf) (look at managedBean) and it is working with weld v2.4.6. on Tomcat 8.5. Could you, please, supply minimal application which fails?

**Comment by svelto-spinoff** [comment]
Thanks a lot for your answer. In fact, we tried your test application, and saw that it uses OpenWebBeans rather than Weld as a CDI implementation.
We can confirm that the HotSwap agent works fine with OpenWebBeans. However, we still fail to make it work with Weld.

**Comment by skybber** [comment]
I've updated example project, so it's using Weld  by default now. There is `hotswap-agent.properties` config file in the project resources (it is found by HA when applications is starting automatically) with traces logging turn on. In your case, the bean is probably not redefined in BeanManager, since bean archive is not found by HA. Bean archives are registered in `BeanClassRefreshAgent.java`, you should see bean archive registrations log messages on app start in this form:

    "BeanClassRefreshAgent registerArchive bdaId= ...."

After bean class modification you should see following log msg (from `WeldPlugin.java`):

    "Class {} redefined for archive {}"

Please send me the your weld and container versions. Thank you for help with resolving this bug.

**Comment by svelto-spinoff** [comment]
Hi. I think that this is an issue related to the weld version. I confirm that using weld v.2.4.6 the HA works fine. In my previous tests I was using a newer version (3.0.2/3.0.3), and with them the beans are not redefined (I tried also changing the weld version in the example project, and I confirm the issue).
I think that I will downgrade weld in my projects until a fix will be released.

Thanks again for your support
