### ISSUE TITLE
can we use this method in production ?

### ISSUE THREAD

**Issue by prtsh716** [HotswapProjects/HotswapAgent#321]
Is it right method to use in production as well. if not could any one explain me in details why so ?

**Comment by skybber** [comment]
It's not recommended due:

- JVM very rarely crashes after redefinition. So it's not 100% stable especially after massive redefinition
- not all redefinitions are supported by dcevm, e.g. change of supper class
- dcevm+HA can't solve all corner cases. For instance you modify initialization of field in constructor of class A, then all existing instances of A could have inconsistent state. So always you have to know, what you are doing and what consequences redefinition could have.
- dcevm8 could be slower since it use serial GC, dcevm11 could be faster if you turn ON ConcurrentMS GC
- redefinition discards JVM code cache, so application is little bit slower for several seconds after hotswap.

So I don't recommend it especially for enterprise applications.
