### ISSUE TITLE
Need a way to reload Spring beans when class signature not changed

### ISSUE THREAD

**Issue by aekrylov** [HotswapProjects/HotswapAgent#324]
I'm using Spring components with state initialized in a PostConstruct method and a couple of changing private methods. Currently, if I change initialization method body and then reload the class, the correspoding bean will not reinitialize its state, because beans are reloaded only when class isgnature is changed. 
[Here](https://github.com/Mikord/HotswapAgent/blob/feature/SUPPORT-3914_no_hotswap/plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/SpringPluginTest.java#L162) is a simple test case, demonstrating my use case, that fails. i.e.

```java
@Component
public class BeanPostConstructImpl implements BeanPostConstruct {
//..
  @PostConstruct
  public void b() {
    value = oldMethod();
  }

  private String oldMethod() {
    return "old value";
  }
//..
}
```

is being changed to 
```java
//...
  @PostConstruct
  public void b() {
    value = newMethod();
  }

  private String oldMethod() {
    return "old value";
  }

  private String newMethod() {
    return "new value";
  }
//...
```

Is there a way to re-initialize the bean even if public class members remain the same?

**Comment by skybber** [comment]
Appropriate code in SpringPlugin related to your issue is [here](https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/SpringChangesAnalyzer.java#L61) . May be it could be done better - check byte code changes of constructor/@PostConctruct methods, analyze it.... But it is pretty hard to solve all corner cases. HA does not do it.

**Comment by skybber** [comment]
I'm closing it since reinicialization of existing instances of modified class based on bytecode interpretation of modified constructos or @PostCcontruct is not doable for all corner cases, It is doable only for simple cases, if there is one constructor assigning constants of primitive datatypes to fields.
