### ISSUE TITLE
Logging of hotswap reloads

### ISSUE THREAD

**Issue by chkpnt** [HotswapProjects/HotswapAgent#380]
I'm using the JVM-8-version with Eclipse and it seems to work. 👍 

But I'm wondering that I do not see any RELOAD messages in the console log if the app (Tomcat in my example) is started in debug mode and without `autoHotswap=true`. When I use the latter, I see a line like this
```
HOTSWAP AGENT: 17:31:18.865 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [...] (autoHotswap)
```
From what I tested I'm sure hotswapping is working in debug mode, but I'd like to get some feedback in the console.

**Comment by skybber** [comment]
It is not printed since Hotswapper plugin is disabled if `autoHotswap=true`. Instead of HA plugin, the hotswap is handled by IDE. You can force JVM to print hotswap logs out using `-XX:TraceRedefineClasses=1` in dcevm8. Log infastructure was changed in java11 so that the log option must be used in a new form: `-Xlog:redefine+class*=info`

**Comment by chkpnt** [comment]
That obviously makes sense, thanks!
