### ISSUE TITLE
How should I debug the modified class?

### ISSUE THREAD

**Issue by homejim** [HotswapProjects/HotswapAgent#555]
When using the hotswap agent, some framework classes are modified. I want to debug these framework classes, but during debugging, the source code doesn't match the modified classes. How can I debug the modified classes?

**Comment by skybber** [comment]
You can place modified classes on `extraClasspath` by following the instructions at the 

[HotswapAgent configuration documentation](http://hotswapagent.org/mydoc_configuration.html).

Classes on `extraClasspath` have the highest priority for classloaders. This means that you can put classes typically stored in jar files on extraClasspath, and these classes will be used instead of the ones in the jars. This is a powerful feature, especially when combined with autoHotswap=true.
